name: Message Verifier
on:
  push:
    branches: [ master ]
  pull_request_target:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Import & Verify Messages
        run: ./scripts/import_cicada_3301_key.sh && ./scripts/verify_messages.sh
